packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild